
# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'


add_newline = true
command_timeout = 1000
format = """[╭╴](238)$os$username$hostname$directory$git_branch$git_status
[╰─](238)$character"""

# Prompt character
[character]
success_symbol = "[λ](bold blue) "
error_symbol = "[λ](bold red) "

# Display os symbol
[os]
format = "[$symbol](bold white) " 
disabled = false

# Display username
[username]
style_user = "red bold"
style_root = "green bold"
format = "[$user]($style) "
disabled = false
show_always = true
aliases = { "jokerwin" = "mr.robot"}

# Display hostname
[hostname]
ssh_only = false
format = "on [$hostname](bold yellow) "
disabled = false

# [hostname]
# ssh_symbol = " "

# Display current directory
[directory]
truncation_length = 3
truncation_symbol = '…/'
home_symbol = '󰋜 ~'
style = 'bold cyan'
read_only_style = '197'
read_only = '  '
format = 'at [$path]($style)[$read_only]($read_only_style) '

# [directory]
# read_only = " 󰌾"

# Shows current git branch
[git_branch]
symbol = ' '
format = 'via [$symbol$branch]($style)'
truncation_symbol = '…/'
style = 'bold green'

[git_status]
format = ' [$staged$modified$untracked$ahead_behind]($style) '
style = 'bold green'

staged = '+'
modified = '*'
untracked = '?'

ahead = '⇡${count}'
behind = '⇣${count}'
diverged = '⇕'

# Hide the rest for minimalism
deleted = ''
renamed = ''
stashed = ''
conflicted = ''
up_to_date = ''

[docker_context]
symbol = " "

[gradle]
symbol = " "

[java]
symbol = " "

[kotlin]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[nodejs]
symbol = " "

[os.symbols]
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CachyOS = " "
CentOS = " "
Debian = " "
Fedora = " "
FreeBSD = " "
Ios = "󰀷 "
Kali = " "
Linux = " "
Macos = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = "󰍲 "

[package]
symbol = "󰏗 "

[python]
symbol = " "

[rust]
symbol = "󱘗 "

[status]
symbol = " "
